name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Ionic and Capacitor
        run: |
          npm install -g @ionic/cli @capacitor/cli

      - name: Install dependencies
        run: npm install

      - name: Build web app
        run: npm run build

      - name: Capacitor sync
        run: npx cap sync android

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Build with Gradle
        run: cd android && ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk