name: Android Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: List APK files
        run: find android -name "*.apk"

      - name: Create output directory
        run: mkdir -p output

      - name: Copy APK to output directory
        run: cp android/app/build/outputs/apk/debug/app-debug.apk output/

      # Esta opción usa el almacenamiento de GitHub artifacts pero no usa la acción upload-artifact
      - name: Archive production artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: output