name: Basic Android Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: List project structure
        run: ls -la

      - name: Install dependencies
        run: npm install

      - name: Update build.gradle
        run: |
          if [ -f android/app/build.gradle ]; then
            sed -i 's/sourceCompatibility JavaVersion.VERSION_21/sourceCompatibility JavaVersion.VERSION_17/g' android/app/build.gradle
            sed -i 's/targetCompatibility JavaVersion.VERSION_21/targetCompatibility JavaVersion.VERSION_17/g' android/app/build.gradle
          fi

      - name: Create dist folder
        run: |
          mkdir -p dist
          echo "<html><body>Placeholder</body></html>" > dist/index.html

      - name: Sync with Capacitor
        run: npx cap sync android

      - name: Build with Gradle
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Check for APK
        run: |
          find android -name "*.apk"
          ls -la android/app/build/outputs/apk/debug/ || echo "No APK directory found"