name: Android Build with Docker

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build with Docker
        run: |
          docker run --rm -v $(pwd):/project -w /project node:20 bash -c "npm install && mkdir -p dist && echo '<html><body>App</body></html>' > dist/index.html && npx cap sync android"
          docker run --rm -v $(pwd):/project -w /project/android openjdk:17 bash -c "chmod +x ./gradlew && ./gradlew assembleDebug"

      - name: List APK files
        run: find android -name "*.apk"