name: Android Build with Java 21
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# Corrección de la sección de permisos
permissions:
  contents: write  # Permite escribir en el contenido del repositorio
  # Las siguientes líneas son las que causan el problema
  # packages: write
  # releases: write  # 'releases' no es un permiso válido

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Generate version
        id: version
        run: echo "version=$(date +'%Y%m%d_%H%M')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm install

      - name: Create dist folder
        run: |
          mkdir -p dist
          echo "<html><body>Placeholder</body></html>" > dist/index.html

      - name: Sync with Capacitor
        run: npx cap sync android

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > android/local.properties

      - name: Build debug APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Find APK
        run: find android -name "*.apk"

      - name: Create versioned APK
        run: |
          mkdir -p versioned-apk
          cp $(find android -name "app-debug.apk") versioned-apk/ExpenseTracker-${{ steps.version.outputs.version }}.apk
          echo "APK con versión creado en: versioned-apk/ExpenseTracker-${{ steps.version.outputs.version }}.apk"
          ls -la versioned-apk/

      - name: Create version info file
        run: |
          echo "Version: ${{ steps.version.outputs.version }}" > versioned-apk/version.txt
          echo "Build date: $(date)" >> versioned-apk/version.txt
          echo "Commit: $(git rev-parse HEAD)" >> versioned-apk/version.txt

      # Usar upload-artifact v3
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ExpenseTracker-APK
          path: versioned-apk/
          retention-days: 30